name: Release Package to npm

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to checkout the code
      id-token: write # Needed for provenance generation (optional but recommended)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun test

      - name: Build package
        run: bun run build

      - name: Setup Node.js for npm publish
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use an LTS version of Node.js
          registry-url: 'https://registry.npmjs.org/'

      - name: Publish to npm
        run: npm publish --access public # Assuming public package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use secret for npm token

      # Optional: Generate release notes or create GitHub Release
      # - name: Create GitHub Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this release:
      #       - TODO: Add release notes here or link to CHANGELOG
      #     draft: false
      #     prerelease: false